builds:
  - env: [CGO_ENABLED=0]
    flags:
      - -trimpath
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - "386"
      - "amd64"
      - "arm"
      - "arm64"
      - "mips"
    gomips:
      - hardfloat
      - softfloat
    mod_timestamp: '{{ .CommitTimestamp }}'
dockers:
- image_templates: ["ghcr.io/traidento/dnsd:{{ .Version }}"]
  use: buildx
  dockerfile: Dockerfile
  build_flag_templates:
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description=Lightweight DDNS daemon
  - --label=org.opencontainers.image.url=https://github.com/traidento/dnsd
  - --label=org.opencontainers.image.source=https://github.com/traidento/dnsd
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2022-05-02T16:09:08+08:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT
